language: julia

os:
  - linux
  - osx

julia:
  - 0.6
  - 0.7
  - nightly

matrix:
  allow_failures:
    - julia: nightly

after_success:
  # push coverage results to Coveralls
  - julia -e "VERSION >= v\"0.7.0-DEV.5183\" && using Pkg; Pkg.add(\"Coverage\"); using Coverage; Coveralls.submit(Coveralls.process_folder())"
