language: julia

os:
  - linux
  - osx

julia:
  - 0.6
  - 0.7
  - nightly

matrix:
  allow_failures:
    - julia: nightly

notifications:
  email: false

after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir(\"${JL_PKG}\")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
