name = "MetaRowEchelon"
uuid = "a9a8b776-935c-11e8-0e2d-397ddf4dd959"
authors = ["Jonathan Goldfarb <jgoldfar@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
